
__all__ = ["UIDMixin", "NameMixin"]


class UIDMixin:
    """Support UID generated by uuid4()."""
    _uid: int | None = None

    def __init__(self, *, uid: int | None = None) -> None:
        self._uid = uid

    @property
    def uid(self) -> int:
        """Get unique ID of the object."""
        if self._uid is None:
            from uuid import uuid4
            self._uid = int(uuid4())

        return self._uid


class NameMixin:
    """Support unique names for __repr__."""
    _uname: str | None = None

    def __repr__(self) -> str:
        type_name = self.__class__.__name__

        if self._uname:
            return "{}({})".format(type_name, self._uname)

        return super().__repr__()

    @property
    def uname(self):
        if self._uname:
            return self._uname

        return super().__repr__()

    def set_name(self, name: str | None, /):
        self._uname = name
